import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:shared_preferences/shared_preferences.dart';

/// Lightweight auth service wrapping Firestore `users` collection
/// and SharedPreferences session management.
///
/// Fields in each user document: `username`, `pin`.
/// Document ID is auto-generated by Firestore.
class AuthService {
  static const _sessionKey = 'logged_in_username';

  final CollectionReference<Map<String, dynamic>> _usersRef =
      FirebaseFirestore.instance.collection('users');

  // ── Firestore operations ──────────────────────────────────────────────

  /// Returns `true` if a document with [username] already exists.
  Future<bool> usernameExists(String username) async {
    final snapshot = await _usersRef
        .where('username', isEqualTo: username)
        .limit(1)
        .get();
    return snapshot.docs.isNotEmpty;
  }

  /// Creates a new user document with [username] and [pin].
  ///
  /// Returns the auto-generated document ID.
  /// Throws a [StateError] if the username is already taken.
  Future<String> createUser(String username, String pin) async {
    if (await usernameExists(username)) {
      throw StateError('Username "$username" is already taken.');
    }
    final docRef = await _usersRef.add({
      'username': username,
      'pin': pin,
    });
    return docRef.id;
  }

  /// Validates [username] + [pin] against Firestore.
  ///
  /// Returns the document ID on success, `null` on mismatch.
  Future<String?> login(String username, String pin) async {
    final snapshot = await _usersRef
        .where('username', isEqualTo: username)
        .where('pin', isEqualTo: pin)
        .limit(1)
        .get();
    if (snapshot.docs.isEmpty) return null;
    return snapshot.docs.first.id;
  }

  // ── Session persistence (SharedPreferences) ───────────────────────────

  /// Persists [username] so the app can skip login on restart.
  Future<void> saveSession(String username) async {
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_sessionKey, username);
  }

  /// Returns the previously saved username, or `null` if none.
  Future<String?> getSavedSession() async {
    final prefs = await SharedPreferences.getInstance();
    return prefs.getString(_sessionKey);
  }

  /// Removes the saved session (logout).
  Future<void> clearSession() async {
    final prefs = await SharedPreferences.getInstance();
    await prefs.remove(_sessionKey);
  }
}
