// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg6iWRw3Ul36NB46vrQVH71wEnuULFFEU',
    appId: '1:765190497180:web:6b7ed27c99d4fa4db09e59',
    messagingSenderId: '765190497180',
    projectId: 'daily-journal-abfa9',
    authDomain: 'daily-journal-abfa9.firebaseapp.com',
    storageBucket: 'daily-journal-abfa9.firebasestorage.app',
    measurementId: 'G-TY8R8EM461',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2PdpzBUmIdXlt8io1cswkEF9Dvv4JdEc',
    appId: '1:765190497180:android:7bade4a8cd86409fb09e59',
    messagingSenderId: '765190497180',
    projectId: 'daily-journal-abfa9',
    storageBucket: 'daily-journal-abfa9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCoj44EiQfSjLFn6ROJaagioYcxuib5yM',
    appId: '1:765190497180:ios:ad0414be8297e652b09e59',
    messagingSenderId: '765190497180',
    projectId: 'daily-journal-abfa9',
    storageBucket: 'daily-journal-abfa9.firebasestorage.app',
    iosBundleId: 'com.example.flutterFinalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCoj44EiQfSjLFn6ROJaagioYcxuib5yM',
    appId: '1:765190497180:ios:ad0414be8297e652b09e59',
    messagingSenderId: '765190497180',
    projectId: 'daily-journal-abfa9',
    storageBucket: 'daily-journal-abfa9.firebasestorage.app',
    iosBundleId: 'com.example.flutterFinalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBg6iWRw3Ul36NB46vrQVH71wEnuULFFEU',
    appId: '1:765190497180:web:f198edacd71f3644b09e59',
    messagingSenderId: '765190497180',
    projectId: 'daily-journal-abfa9',
    authDomain: 'daily-journal-abfa9.firebaseapp.com',
    storageBucket: 'daily-journal-abfa9.firebasestorage.app',
    measurementId: 'G-S2FTS4H8YC',
  );
}
